spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/twitterclonedb
    username: root
    password: 12345